sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update
install:
  - pip install pytest pytest-cov coveralls pep8
  - python setup.py install
script:
  - python -m py.test -v --cov=marc2excel test/
  - pep8
after_success:
  - coveralls